In [1]:
import numpy as np
import scipy.stats
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Generating affinity matrix, using department partition as shown by Huseyin

P = 30 #num professors
num_departments = 7 #num departments
preference_prob = .5 #prob of professor i within department d liking professor j within same department
 
C = np.zeros((P,P))

partitions = np.random.randint(0,P,size = num_departments - 1)
partitions.sort()
partitions = np.append(partitions,P)


last_p = 0
for p in partitions:
    C[last_p:p,last_p:p] = np.random.binomial(1,preference_prob, size = (p - last_p,p - last_p))
    last_p = p

for i in range(0,P):
    C[i,i] = 1
    
print(partitions)
print(C)



[10 12 13 15 18 19 30]
[[1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0

In [3]:
#generating room preferences

#hard-coded room numbers
second_floor_rooms = [201,205,210,212,214,216,218,220,238,
                      252,254,255,256,257,259,260,261,262,
                      263,264,265,266,267,268,270,271,273,
                      275,277,287,289,291,293]
third_floor_rooms = [int('3' + str(num)[1:]) for num in second_floor_rooms]
room_list = second_floor_rooms + third_floor_rooms
random.shuffle(room_list)
num_rooms = len(room_list)
num_rankings = 4

#R_ is num_professors x num_ranking matrix, R_ik is the kth choice room number for professor i
R_ = np.zeros((P,num_rankings))

#uniform case: generates room rankings for each professor, assuming all rooms are equally preferred 
for i in range(P):
    R_[i] = np.random.choice(room_list, size=num_rankings, replace=False, p=None)

#weighted case: generates room rankings for each professor, assuming room preferences follow a geometric distribution ~geom(p)  
p = .2
room_probs = [scipy.stats.geom.pmf(k,p) for k in range(1,num_rooms+1)]
room_probs[-1] = 1 - min(sum(room_probs[:-1]),1)

for i in range(P):
    R_[i] = np.random.choice(room_list, size=num_rankings, replace=False, p=room_probs)
    
#R is num_professors x num_room X num_ranking matrix, 
#R_ijk is 1 if professor i's kth ranked room is the jth element of room_list
R= np.zeros((P,num_rooms,num_rankings))
for i in range(P):
    for j in range(len(room_list)):
        for k in range(num_rankings):
            if R_[i,k]==room_list[j]:
                R[i,j,k]=1
                


In [4]:
num_floors = 2
lowest_floor = 2
#F is num_professors X num floors matrix where F_il = 1 if professor i wants to sit on floor l
F = np.zeros((P,num_floors))
#if professor i chose a room on floor l in his rankings R_, then we assume she wants to sit on that floor
for i in range(P):
    floor_nums_for_i = [int(str(n)[0]) - lowest_floor for n in R_[i]]
    for l in floor_nums_for_i:
        F[i,l] = 1
F

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])